#!/usr/bin/env bash
# 受入基準 → 満たす DES → 確かめるテスト の対応表を生成する(生成ビュー。手で書かない)。
# 使い方: spec-trace.sh <spec> [project-root] [--write]   --write で specs/{spec}/trace.md に書く
set -euo pipefail
# shellcheck source=lib/common.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"

spec="${1:?usage: spec-trace.sh <spec> [project-root] [--write]}"
shift
write=0; rootarg=""
for a in "$@"; do case "$a" in --write) write=1 ;; *) rootarg="$a" ;; esac; done
root="$(spec_project_root "$rootarg")"

out="$(spec_index "$root" "$spec" | gawk -F'\t' '
  function trim(s) { sub(/^[[:space:]]+/, "", s); sub(/[[:space:]]+$/, "", s); return s }
  $1 == "ac" { acs[++n] = $3; next }
  $1 == "def" { order[++nd] = $3; next }
  $1 == "field" { F[$3, $4] = $5; next }
  END {
    for (j = 1; j <= nd; j++) {
      id = order[j]
      if (id ~ /^DES-/) { m = split(F[id, "Satisfies"], a, /,[[:space:]]*/); for (i = 1; i <= m; i++) by[trim(a[i])] = by[trim(a[i])] (by[trim(a[i])] == "" ? "" : ", ") id }
      if (id ~ /^(UT|CT|IT|ST|E2E)-/) { m = split(F[id, "Verifies"], a, /,[[:space:]]*/); for (i = 1; i <= m; i++) ver[trim(a[i])] = ver[trim(a[i])] (ver[trim(a[i])] == "" ? "" : ", ") id }
    }
    print "<!-- GENERATED by spec-trace.sh: do not edit -->"
    print "| 受入基準 | 満たす DES | 確かめるテスト |"
    print "|---|---|---|"
    for (i = 1; i <= n; i++) print "| " acs[i] " | " (by[acs[i]] == "" ? "-" : by[acs[i]]) " | " (ver[acs[i]] == "" ? "-" : ver[acs[i]]) " |"
  }')"

if (( write )); then
  printf '%s\n' "$out" > "$(spec_dir "$root" "$spec")/trace.md"
else
  printf '%s\n' "$out"
fi
